/**
 * Home constants
 */

export const GET_HOME_DATA_SUCCESS = 'GET_HOME_DATA_SUCCESS';
export const GET_HOME_DATA_ERROR = 'GET_HOME_DATA_ERROR';

/**
 * Article constants
 */

export const GET_ALL_BLOG_DATA_SUCCESS = 'GET_ALL_BLOG_DATA_SUCCESS';
export const GET_ALL_BLOG_DATA_ERROR = 'GET_ALL_BLOG_DATA_ERROR';
export const GET_LAST_BLOG_DATA_SUCCESS = 'GET_LAST_BLOG_DATA_SUCCESS';
export const GET_LAST_BLOG_DATA_ERROR = 'GET_LAST_BLOG_DATA_ERROR';

/**
 * About me constants
 */

export const GET_ABOUT_ME_DATA_SUCCESS = 'GET_ABOUT_ME_DATA_SUCCESS';
export const GET_ABOUT_ME_DATA_ERROR = 'GET_ABOUT_ME_DATA_ERROR';
